name: Publish docker image

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag to release (e.g. v1.2.3)'
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        if: startsWith(github.event.inputs.release_tag, 'v')
        steps:
        - name: Harden the runner (Audit all outbound calls)
          uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
          with:
            egress-policy: audit

        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        - name: Validate tag format
          run: |
            TAG=${{ github.event.inputs.release_tag }}
            if ! echo "$TAG" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
              echo "❌ Invalid tag format: $TAG"
              exit 1
            fi
            echo "✅ Valid semver tag: $TAG"
        - name: install docker emulation
          run: docker run --rm --privileged tonistiigi/binfmt:latest --install amd64,arm64
        - name: Set up buildx
          uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        - name: Login to ghcr.io
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        - name: Build and push
          run: |
            docker buildx build --platform linux/amd64,linux/arm64 -t $(echo 'ghcr.io/${{ github.repository }}:${{ github.event.inputs.release_tag }}' | tr '[:upper:]' '[:lower:]') --push .
